import kDict
test={
      'a':123,
      'b':{
         'c':{'ddd'},
         'e':{}
      }
    }
root=kDict.kDict(test)
root.tree.apple.color='red'
root.tree.apple.PUT('color','red')
root.tree.banana.PUT('color','yellow')
root.tree.banana.PUT('banana2','white')
root.tree.banana.PUT('banana3','yellow')
root.tree.banana.color.PROPER('readonly',True)
root.tree.apple['color']='red'
root.tree.apple.color.GET()
root.tree.apple.GET('color')
root.tree.apple.color.PROPER('readonly',True)
root.tree.apple.PUT('color','white')
root.tree.apple.color.PROPER('readonly',False)
root.tree.apple.PUT('color','white')
root.PRINT()
print(root.FIND('readonly',proper=True))
print(root.FIND('apple',mode='key'))
print(root.FIND('white'))
